
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  dsa: [{ type: 'autogenerated', dirName: 'dsa', }],
  javascript: [{ type: 'autogenerated', dirName: 'javascript', }],
  typescript: [{ type: 'autogenerated', dirName: 'typescript', }],
  react: [{ type: 'autogenerated', dirName: 'react', }],
  python: [{ type: 'autogenerated', dirName: 'python', }],
  cpp: [{ type: 'autogenerated', dirName: 'cpp', }],
  java: [{ type: 'autogenerated', dirName: 'java', }],
  html: [{ type: 'autogenerated', dirName: 'html', }],
  tailwindcss: [{ type: 'autogenerated', dirName: 'tailwind', }],
};

export default sidebars;
