// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    "index",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        "installation",
        "configuration",
        "playground",
        "typescript-support",
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Docusaurus Guides",
        description:
          "Let's learn about the most important Docusaurus concepts!",
        keywords: ["guides"],
        image: "/img/nav-logo.jpg",
      },
      items: [
        "guides/creating-pages",
        {
          type: "category",
          label: "Docs",
          link: {
            type: "doc",
            id: "guides/docs/introduction",
          },
          items: [
            "guides/docs/create-doc",
            {
              type: "category",
              label: "Sidebar",
              link: {
                type: "doc",
                id: "guides/docs/sidebar/index",
              },
              items: [
                "guides/docs/sidebar/items",
                "guides/docs/sidebar/autogenerated",
                "guides/docs/sidebar/multiple-sidebars",
              ],
            },
            "guides/docs/versioning",
            "guides/docs/multi-instance",
          ],
        },
        "blog",
        {
          type: "category",
          label: "Markdown Features",
          link: {
            type: "doc",
            id: "guides/markdown-features/introduction",
          },
          items: ["guides/markdown-features/react"],
        },
        'styling-layout',
        'browser-support',
        "seo",
      ],
    },
  ],
};

export default sidebars;
