
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  dsa: [{ type: 'autogenerated', dirName: 'dsa', }],
  javascript: [{ type: 'autogenerated', dirName: 'javascript', }],
  typescript: [{ type: 'autogenerated', dirName: 'typescript', }],
  react: [{ type: 'autogenerated', dirName: 'react', }],
  python: [{ type: 'autogenerated', dirName: 'python', }],
};

export default sidebars;
