module.exports = {
  codeharborhub: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  excelSidebar: [
    {
      type: "category",
      label: "Excel Masterclass",
      link: {
        type: "generated-index",
        title: "Excel Masterclass Overview",
        description:
          "Explore our complete 12-module Excel guide covering everything from basic entry to advanced DAX and VBA automation.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "excel",
        },
      ],
    },
  ],
};
