module.exports = {
    codeharborhub: [ 
      {
        type: "autogenerated",
        dirName: ".",
      },
      {
        type: 'link',
        label: 'DSA Problems',
        href: '/dsa-problems',
      },
      {
        type: 'link',
        label: 'DSA Solutions',
        href: '/dsa-solutions',
      },
    ],
  };