
const arrays = [
  {
    id: 1,
    problemName: "1. Two Sum",
    difficulty: "Easy",
    catagoery: ["Array", "Hash Table"],
    algorithm: ["Brute Force", "Two Pointers", "Hash Table"],
    leetCodeLink: "https://leetcode.com/problems/two-sum/",
    solutionLink: "#",
  },
  {
    id: 2,
    problemName: "2. Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    catagoery: ["Array", "Dynamic Programming"],
    algorithm: [
      "Brute Force",
      "One Pass",
      "Divide and Conquer",
      "Dynamic Programming",
    ],
    leetCodeLink:
      "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    solutionLink: "#",
  },
  {
    id: 3,
    problemName: "3. Contains Duplicate",
    difficulty: "Easy",
    catagoery: ["Array", "Hash Table"],
    algorithm: ["Brute Force", "Sorting", "Hash Table"],
    leetCodeLink: "https://leetcode.com/problems/contains-duplicate/",
    solutionLink: "#",
  },
  {
    id: 4,
    problemName: "4. Product of Array Except Self",
    difficulty: "Medium",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "Prefix Sum", "Suffix Sum", "Two Pointers"],
    leetCodeLink: "https://leetcode.com/problems/product-of-array-except-self/",
    solutionLink: "#",
  },
  {
    id: 5,
    problemName: "5. Maximum Subarray",
    difficulty: "Easy",
    catagoery: ["Array", "Divide and Conquer", "Dynamic Programming"],
    algorithm: ["Brute Force", "Divide and Conquer", "Dynamic Programming"],
    leetCodeLink: "https://leetcode.com/problems/maximum-subarray/",
    solutionLink: "#",
  },
  {
    id: 6,
    problemName: "6. Maximum Product Subarray",
    difficulty: "Medium",
    catagoery: ["Array", "Dynamic Programming"],
    algorithm: ["Brute Force", "Dynamic Programming"],
    leetCodeLink: "https://leetcode.com/problems/maximum-product-subarray/",
    solutionLink: "#",
  },
  {
    id: 7,
    problemName: "7. Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    catagoery: ["Array", "Binary Search"],
    algorithm: ["Brute Force", "Binary Search"],
    leetCodeLink:
      "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    solutionLink: "#",
  },
  {
    id: 8,
    problemName: "8. Search in Rotated Sorted Array",
    difficulty: "Medium",
    catagoery: ["Array", "Binary Search"],
    algorithm: ["Brute Force", "Binary Search"],
    leetCodeLink:
      "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    solutionLink: "#",
  },

  {
    id: 9,
    problemName: "9. 3Sum",
    difficulty: "Medium",
    catagoery: ["Array", "Two Pointers"],
    algorithm: ["Brute Force", "Two Pointers"],
    leetCodeLink: "https://leetcode.com/problems/3sum/",
    solutionLink: "#",
  },
  {
    id: 10,
    problemName: "10. Container With Most Water",
    difficulty: "Medium",
    catagoery: ["Array", "Two Pointers"],
    algorithm: ["Brute Force", "Two Pointers"],
    leetCodeLink: "https://leetcode.com/problems/container-with-most-water/",
    solutionLink: "#",
  },
  {
    id: 11,
    problemName: "11. Best Time to Buy and Sell Stock II",
    difficulty: "Easy",
    catagoery: ["Array", "Greedy"],
    algorithm: ["Brute Force", "Greedy"],
    leetCodeLink:
      "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
    solutionLink: "#",
  },
  {
    id: 12,
    problemName: "12. Find All Numbers Disappeared in an Array",
    difficulty: "Easy",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "Hash Table"],
    leetCodeLink:
      "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/",
    solutionLink: "#",
  },
  {
    id: 13,
    problemName: "13. Spiral Matrix",
    difficulty: "Medium",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "Simulation"],
    leetCodeLink: "https://leetcode.com/problems/spiral-matrix/",
    solutionLink: "#",
  },
  {
    id: 14,
    problemName: "14. Jump Game",
    difficulty: "Medium",
    catagoery: ["Array", "Greedy"],
    algorithm: ["Brute Force", "Greedy"],
    leetCodeLink: "https://leetcode.com/problems/jump-game/",
    solutionLink: "#",
  },
  {
    id: 15,
    problemName: "15. Merge Intervals",
    difficulty: "Medium",
    catagoery: ["Array", "Sorting"],
    algorithm: ["Brute Force", "Sorting"],
    leetCodeLink: "https://leetcode.com/problems/merge-intervals/",
    solutionLink: "#",
  },

  {
    id: 16,
    problemName: "16. Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    catagoery: ["Array", "Binary Search"],
    algorithm: ["Brute Force", "Binary Search"],
    leetCodeLink:
      "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    solutionLink: "#",
  },
  {
    id: 17,
    problemName: "17. Search in Rotated Sorted Array II",
    difficulty: "Medium",
    catagoery: ["Array", "Binary Search"],
    algorithm: ["Brute Force", "Binary Search"],
    leetCodeLink:
      "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/",
    solutionLink: "#",
  },
  {
    id: 18,
    problemName: "18. Valid Sudoku",
    difficulty: "Medium",
    catagoery: ["Array", "Hash Table"],
    algorithm: ["Brute Force", "Hash Table"],
    leetCodeLink: "https://leetcode.com/problems/valid-sudoku/",
    solutionLink: "#",
  },
  {
    id: 19,
    problemName: "19. Rotate Image",
    difficulty: "Medium",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "In-Place"],
    leetCodeLink: "https://leetcode.com/problems/rotate-image/",
    solutionLink: "#",
  },
  {
    id: 20,
    problemName: "20. Set Matrix Zeroes",
    difficulty: "Medium",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "In-Place"],
    leetCodeLink: "https://leetcode.com/problems/set-matrix-zeroes/",
    solutionLink: "#",
  },
  {
    id: 21,
    problemName: "21. Plus One",
    difficulty: "Easy",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "Simulation"],
    leetCodeLink: "https://leetcode.com/problems/plus-one/",
    solutionLink: "#",
  },
  {
    id: 22,
    problemName: "22. Minimum Size Subarray Sum",
    difficulty: "Medium",
    catagoery: ["Array", "Two Pointers", "Binary Search"],
    algorithm: ["Brute Force", "Two Pointers", "Binary Search"],
    leetCodeLink: "https://leetcode.com/problems/minimum-size-subarray-sum/",
    solutionLink: "#",
  },

  {
    id: 23,
    problemName: "23. Longest Increasing Subsequence",
    difficulty: "Medium",
    catagoery: ["Array", "Binary Search", "Dynamic Programming"],
    algorithm: ["Brute Force", "Dynamic Programming"],
    leetCodeLink:
      "https://leetcode.com/problems/longest-increasing-subsequence/",
    solutionLink: "#",
  },
  {
    id: 24,
    problemName: "24. Search a 2D Matrix",
    difficulty: "Medium",
    catagoery: ["Array", "Binary Search"],
    algorithm: ["Brute Force", "Binary Search"],
    leetCodeLink: "https://leetcode.com/problems/search-a-2d-matrix/",
    solutionLink: "#",
  },
  {
    id: 25,
    problemName: "25. Find the Duplicate Number",
    difficulty: "Medium",
    catagoery: ["Array", "Two Pointers", "Binary Search"],
    algorithm: ["Brute Force", "Two Pointers", "Binary Search"],
    leetCodeLink: "https://leetcode.com/problems/find-the-duplicate-number/",
    solutionLink: "#",
  },
  {
    id: 26,
    problemName: "26. Spiral Matrix II",
    difficulty: "Medium",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "Simulation"],
    leetCodeLink: "https://leetcode.com/problems/spiral-matrix-ii/",
    solutionLink: "#",
  },
  {
    id: 27,
    problemName: "27. Missing Number",
    difficulty: "Easy",
    catagoery: ["Array", "Math", "Bit Manipulation"],
    algorithm: ["Brute Force", "Bit Manipulation"],
    leetCodeLink: "https://leetcode.com/problems/missing-number/",
    solutionLink: "#",
  },
  {
    id: 28,
    problemName: "28. First Missing Positive",
    difficulty: "Hard",
    catagoery: ["Array", "Hash Table"],
    algorithm: ["Brute Force", "Hash Table"],
    leetCodeLink: "https://leetcode.com/problems/first-missing-positive/",
    solutionLink: "#",
  },
  {
    id: 29,
    problemName: "29. Find All Duplicates in an Array",
    difficulty: "Medium",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "Hash Table"],
    leetCodeLink:
      "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
    solutionLink: "#",
  },
  {
    id: 30,
    problemName: "30. Merge Sorted Array",
    difficulty: "Easy",
    catagoery: ["Array", "Two Pointers"],
    algorithm: ["Brute Force", "Two Pointers"],
    leetCodeLink: "https://leetcode.com/problems/merge-sorted-array/",
    solutionLink: "#",
  },
  {
    id: 31,
    problemName: "31. Shortest Unsorted Continuous Subarray",
    difficulty: "Medium",
    catagoery: ["Array"],
    algorithm: ["Brute Force", "Sorting"],
    leetCodeLink:
      "https://leetcode.com/problems/shortest-unsorted-continuous-subarray/",
    solutionLink: "#",
  },
  {
    id: 32,
    problemName: "32. Find All Anagrams in a String",
    difficulty: "Medium",
    catagoery: ["Array", "Hash Table"],
    algorithm: ["Brute Force", "Hash Table"],
    leetCodeLink:
      "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
    solutionLink: "#",
  },
  {
    id: 33,
    problemName: "33. Subarray Product Less Than K",
    difficulty: "Medium",
    catagoery: ["Array", "Two Pointers", "Binary Search"],
    algorithm: ["Brute Force", "Two Pointers"],
    leetCodeLink: "https://leetcode.com/problems/subarray-product-less-than-k/",
    solutionLink: "#",
  },
  {
    id: 34,
    problemName: "34. Minimum Window Substring",
    difficulty: "Hard",
    catagoery: [
      "Array",
      "Hash Table",
      "Two Pointers",
      "String",
      "Sliding Window",
    ],
    algorithm: ["Brute Force", "Two Pointers", "Sliding Window"],
    leetCodeLink: "https://leetcode.com/problems/minimum-window-substring/",
    solutionLink: "#",
  },
  {
    id: 35,
    problemName: "35. Permutation in String",
    difficulty: "Medium",
    catagoery: ["Array", "Two Pointers", "String", "Sliding Window"],
    algorithm: ["Brute Force", "Two Pointers", "Sliding Window"],
    leetCodeLink: "https://leetcode.com/problems/permutation-in-string/",
    solutionLink: "#",
  },
];


export default arrays;