name: "Blog & Content Contributor Request"
description: "Apply to join the Blog & Content Writing team at CodeHarborHub"
title: "Blog & Content Contribution Request: <Your Name>"
labels: ["content-request", "onboarding"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Welcome!  
        Thank you for your interest in contributing to **CodeHarborHub Blogs & Content**.  
        Please fill in the details below to help us onboard you smoothly.

  - type: input
    id: full-name
    attributes:
      label: "Full Name"
      placeholder: "Ajay Dhangar"
      description: "Enter your complete name."
    validations:
      required: true

  - type: input
    id: github-username
    attributes:
      label: "GitHub Username"
      placeholder: "ajay-dhangar"
      description: "Provide your GitHub username."
    validations:
      required: true

  - type: textarea
    id: writing-background
    attributes:
      label: "Writing Experience / Background"
      description: "Share your writing skills, blog experience, niches, or examples."
      placeholder: |
        Example:
        - Technical content writing
        - Web development tutorials
        - AI & Machine Learning concepts
        - Educational blogs
    validations:
      required: true

  - type: textarea
    id: preferred-topics
    attributes:
      label: "Topics You Want to Write About"
      description: "Tell us your top choices for content creation."
      placeholder: |
        Examples:
        - JavaScript tutorials
        - Full-stack development
        - DevOps guides
        - AI/ML concepts
        - Roadmap articles
        - Productivity and learning tips
    validations:
      required: true

  - type: dropdown
    id: content-type
    attributes:
      label: "Preferred Content Type"
      options:
        - "Tutorial"
        - "Blog Article"
        - "Documentation Page"
        - "How-to Guide"
        - "Case Study"
        - "SEO Optimized Post"
    validations:
      required: true

  - type: input
    id: sample-work
    attributes:
      label: "Links to Your Previous Content"
      description: "Share links to blogs, articles, GitHub repos, or writing samples."
      placeholder: "https://medium.com/@yourprofile"
    validations:
      required: false

  - type: input
    id: social-link
    attributes:
      label: "Portfolio / GitHub / LinkedIn"
      description: "Share any one link where we can review your contributions."
      placeholder: "https://github.com/yourusername"
    validations:
      required: true

  - type: dropdown
    id: availability
    attributes:
      label: "Writing Availability"
      description: "How many blogs/guides can you write per month?"
      options:
        - "1"
        - "2"
        - "3"
        - "4+"
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: "Contributor Agreement"
      description: "Please confirm the following:"
      options:
        - label: "I agree to follow the CodeHarborHub Content Guidelines."
          required: true
        - label: "I confirm that all content I write will be original and free of plagiarism."
          required: true
        - label: "I understand that the team may request edits before publishing."
          required: true
