name: "Join Contributors Team"
description: "Request access to join the CodeHarborHub Contributors Team"
title: "Request to Join Contributors Team: <Your Name>"
labels: ["team-request", "onboarding"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in joining the **CodeHarborHub Contributors Team**!  
        Please fill out the details below so we can verify your profile and onboard you smoothly.

  - type: input
    id: full-name
    attributes:
      label: "Full Name"
      description: "Enter your full name."
      placeholder: "Ajay Dhangar"
    validations:
      required: true

  - type: input
    id: github-username
    attributes:
      label: "GitHub Username"
      description: "Provide your GitHub username."
      placeholder: "ajay-dhangar"
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: "Tell us about your background"
      description: "Share a short summary about your skills, learning goals, or experience."
      placeholder: "I am a web developer specializing in React, Node.js, and open-source contributions."
    validations:
      required: true

  - type: textarea
    id: contribution-area
    attributes:
      label: "Preferred Contribution Areas"
      description: "Select or describe the areas you want to contribute in."
      placeholder: |
        Examples:
        - Documentation  
        - Frontend (React, UI/UX)  
        - Backend (Node.js, APIs)  
        - Content Writing  
        - Tutorials  
        - SEO  
        - DevOps  
    validations:
      required: true

  - type: input
    id: portfolio
    attributes:
      label: "Portfolio / GitHub Profile / LinkedIn"
      description: "Share any link where we can review your work."
      placeholder: "https://github.com/yourusername"
    validations:
      required: true

  - type: dropdown
    id: availability
    attributes:
      label: "Weekly Availability"
      description: "How much time can you contribute each week?"
      options:
        - "1–3 hours"
        - "3–6 hours"
        - "6–10 hours"
        - "10+ hours"
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: "Contributor Agreement"
      description: "Please confirm the following:"
      options:
        - label: "I agree to follow the CodeHarborHub Code of Conduct"
          required: true
        - label: "I understand that maintainers may approve or reject team access based on review"
          required: true
        - label: "I will follow contribution guidelines and instructions shared by the team"
          required: true
